#!/bin/sh

umask 077

PROGRAM="$0"
STOREDIR="$HOME/.secstore"

[ ! -d "$STOREDIR" ] && mkdir "$STOREDIR"
cd "$STOREDIR"

[ -z "$EDITOR" ] && EDITOR=vi

die() {
	echo "$@" >&2
	exit 1
}

cmd_help() {
	echo "Help is for the weak. Grow some balls."
	echo "PS: The strong AND smart one would first kill"
	echo "    me for being a dick then properly implement"
	echo "    this function."
}

# Clear clipboard after $1's delay
clear_clipboard() {
	sleep $1
	echo nothing | xsel -b -i
}

cmd_show() {
	if [ -d "$1" ]; then
		cmd_list "" "$1"
	fi

	if [ "$1" == "-c" ]; then
		shift
		output="xsel -b -i"
		clear_clipboard 60 &
	else
		output="cat"
	fi

	[ -z "$1" ] && die "Usage: $PROGRAM show [-c] file-name"
	
	local file="$1.aes"
	[ ! -f "$file" ] && die "$1 does not exist."
	
	get_pass

	echo "$password" | aes -p=/dev/stdin -d "$file" 2> /dev/null | eval "$output" || exit $?
}

cmd_edit() {
	[ -z "$1" ] && die "Usage: $PROGRAM edit file-name"
	
	local file="$1.aes"
	[ ! -f "$file" ] && die "$1 does not exist."

	get_pass

	local tmp=$(mktemp)

	echo "$password" | aes -p=/dev/stdin -o="$tmp" -d "$file" 2> /dev/null
	"$EDITOR" "$tmp"
	echo "$password" | aes -p=/dev/stdin -o="$file" -e "$tmp" 2> /dev/null
	rm "$tmp"
}

cmd_remove() {
	if [ -d "$1" ]; then
		file="$1"
	elif [ -a "$1.aes" ]; then
		file="$1.aes"
	else
		die "$1 does not exist"
	fi

	echo -n "Really remove $file (and possibly subfiles)? [y/n]: "
	read answer
	[ "$answer" != "y" ] && exit
	rm -r "$file"
	echo "Removed $file"
}

cmd_new() {
	local file="$1.aes"
	[ -a "$file" ] && die "$1 already exists"
	
	get_pass

	local tmp=$(mktemp)
	
	"$EDITOR" "$tmp"
	echo "$password" | aes -p=/dev/stdin -o="$file" -e "$tmp" 2> /dev/null
	rm "$tmp"
}

cmd_mkdir() {
	[ -a "$1" ] && die "$1 exists"
	mkdir "$1"
}

cmd_list() {
	cd "$2"
	for f in *; do
		if [ -d "$f" ]; then
			echo "$1$f/"
			cmd_list "$1   /" "$STOREDIR/$2/$f"
			cd "$STOREDIR/$2"
		else
			echo "$1$f" | sed "s/.aes//"
		fi
	done
}

get_pass() {
	echo -n "Enter password: " >&2
	stty -echo
	exec 0</dev/tty
	read password
	echo
	stty echo
}

[ -z "$1" ] && cmd_list "" "." && exit 0

case "$1" in
	init) shift;	cmd_init "${@}" ;;
	help|-h) 	cmd_help ;;
	new) shift;	cmd_new "${@}" ;;
	mkdir) shift;	cmd_mkdir "${@}" ;;
	show) shift;	cmd_show "${@}" ;;
	rm) shift;	cmd_remove "${@}" ;;
	rmdir) shift;   cmd_rmdir "${@}" ;;
	edit) shift;	cmd_edit "${@}" ;;
	*) 		cmd_show "${@}";;
esac
exit 0
