#!/bin/sh

umask 077

PROGRAM="$0"
STOREDIR="$HOME/.secstore"

[ ! -d "$STOREDIR" ] && mkdir "$STOREDIR"
cd "$STOREDIR"

[ -z "$EDITOR" ] && EDITOR=vi

die() {
	echo "$@" >&2
	exit 1
}

cmd_help() {
	echo "Help is for the weak. Grow some balls."
	echo "PS: The strong AND smart one would first kill"
	echo "    me for being a dick then properly implement"
	echo "    this function."
}

cmd_show() {
	if [ -d "$1" ]; then
		cmd_list "" "$1"
		exit 0
	fi

	clipboard=0
	if [ "$1" == "-c" ]; then
		shift
		output="xsel -b -i -t 60000"
		clipboard=1
	else
		output="cat"
	fi

	[ -z "$1" ] && die "Usage: $PROGRAM show [-c] file-name"
	
	local file="$1.aes"
	[ ! -f "$file" ] && die "$1 does not exist."
	
	get_pass
	
	pass=`echo "$password" | aes -p=/dev/stdin -d "$file" 2> /dev/null`

	if [ $clipboard -eq 1 ]; then
		clear_clipboard "$pass" 10 &
	fi

	echo "$pass" | eval "$output"
}

cmd_edit() {
	[ -z "$1" ] && die "Usage: $PROGRAM edit file-name"
	
	local file="$1.aes"
	[ ! -f "$file" ] && die "$1 does not exist."
	
	get_pass
	
	local tmp=$(mktemp)

	(echo "$password" | aes -p=/dev/stdin -d "$file" > "$tmp" 2> /dev/null) || (rm "$tmp" && exit 1) 
	
	"$EDITOR" "$tmp"

	echo "$password" | aes -p=/dev/stdin -e "$tmp" > "$file" 2> /dev/null

	rm "$tmp"
}

cmd_remove() {
	if [ -d "$1" ]; then
		file="$1"
	elif [ -a "$1.aes" ]; then
		file="$1.aes"
	else
		die "$1 does not exist"
	fi

	echo -n "Really remove $file (and possibly subfiles)? [y/n]: "
	read answer
	[ "$answer" != "y" ] && exit
	rm -r "$file"
	echo "Removed $file"
}

cmd_new() {
	local file="$1.aes"
	[ -a "$file" ] && die "$1 already exists"
	
	get_pass

	local tmp=$(mktemp)
	
	"$EDITOR" "$tmp"
	echo "$password" | aes -p=/dev/stdin -e "$tmp" > "$file" 2> /dev/null
	rm "$tmp"
}

cmd_mkdir() {
	[ -a "$1" ] && die "$1 exists"
	mkdir "$1"
}

cmd_list() {
	cd "$STOREDIR/$2"
	for f in *; do
		if [ -d "$f" ]; then
			echo "$1$f/"
			cmd_list "$1   " "$2/$f"
			cd "$STOREDIR/$2"
		else
			echo "$1/$f" | sed "s/.aes//"
		fi
	done
}

get_pass() {
	echo -n "Enter password: " >&2
	stty -echo
	exec 3<&0 # save stdin
	exec 0</dev/tty # re route stdin
	read password
	exec 0<&3 # restore stdin
	stty echo
}

[ -z "$1" ] && cmd_list "" "." && exit 0

case "$1" in
	init) shift;	cmd_init "${@}" ;;
	help|-h) 	cmd_help ;;
	new) shift;	cmd_new "${@}" ;;
	mkdir) shift;	cmd_mkdir "${@}" ;;
	show) shift;	cmd_show "${@}" ;;
	rm) shift;	cmd_remove "${@}" ;;
	rmdir) shift;   cmd_rmdir "${@}" ;;
	edit) shift;	cmd_edit "${@}" ;;
	*) 		cmd_show "${@}";;
esac
exit 0
